### ISSUE TITLE
Предложение добавить недостающие ссылки из gist

### ISSUE THREAD

**Issue by kubk** [codedokode/pasta#12]
В https://gist.github.com/codedokode есть немало полезных ссылок, но навигация по гистам сделана на гитхабе неудобно - нет кнопки для перехода на последнюю страницу, нет оглавления с названием паст для быстрого поиска. Так как некоторые гисты стали популярны, то предлагаю не переносить их в репозиторий pasta, а просто в README в оглавление добавить ссылки на гисты.
Как минимум стоит добавить эти ссылки:
- Задачи на JS: https://gist.github.com/codedokode/ce30e7a036f18f416ae0
- Автоматизированное тестирование: https://gist.github.com/codedokode/a455bde7d0748c0a351a
- TestHub: https://gist.github.com/codedokode/8733007
- ООП калькулятор: https://gist.github.com/codedokode/7005985

Cпасибо.

**Comment by codedokode** [comment]
Добавил все. что было в https://github.com/codedokode/pasta/blob/master/util/README.md.template и во всех гистах, которые перенесены сюда, поставил ссылку на новую версию.
