### ISSUE TITLE
Как хранить в БД древовидные структуры

### ISSUE THREAD

**Issue by YokiToki** [codedokode/pasta#14]
В [пасте](https://github.com/codedokode/pasta/blob/master/db/trees.md) про хранение в БД древовидных структур прочел следующее, в первом варианте.

> И так, пока мы не дойдем до самого младшего ребенка. То есть максимальное число запросов равно глубине дерева + 1 (последним запросом мы проверяем, что больше детей нет). После этого надо еще объединить результаты в дерево и отсортировать в правильном порядке. Часто эта сортировка в итоге требует больше времени, чем выборка.

И думаю, есть ли смысл делать большое количество запросов, когда можно выбрать сразу все. Единственный профит большого количества запросов это контроль уровня вложенности. Либо я что-то упускаю, поясните?

**Comment by codedokode** [comment]
В таблице может быть много записей. Что, если там 10000 записей, а нам нужно всего 20? Это очень сильно понизит производительность. Если число записей в таблице не намного больше, чем выбирается, тогда да, может быть быстрее просто выбрать все и отсортировать на стороне php.

**Comment by YokiToki** [comment]
Как мне кажется, если нужно 20 у нас в любом случае будет критерий по которому мы хотим их получить например `category_id`. А если верхних два слоя дерева, то да, неудобно получается.

**Comment by codedokode** [comment]
Так критерий может быть - "выбрать всех потомков этой записи". Ну например, если есть дерево категорий товаров, нам может потребоваться выбрать всех потомков категории "холодильники". И их там может быть всего несколько штук. И выбирать всю таблицу в таком случае невыгодно.

**Comment by codedokode** [comment]
Закрываю issue. Если будут уточнения или новые вопросы, вы можете создать новый issue.
